services:
  db:
    image: postgres:16
    container_name: ecuador-comparte-db
    restart: always
    environment:
      POSTGRES_DB: ecuador-comparte-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ecuador-comparte-db"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: ecuador-comparte-app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://ecuador-comparte-db:5432/ecuador-comparte-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456789

volumes:
  postgres_data: